# ruff: noqa: A002
from __future__ import annotations

class ParallelOptions:
    def __init__(
        self,
        min_batch_size: int | None = ...,
        chunk_size: int | None = ...,
        max_threads: int | None = ...,
        use_thread_pool: bool | None = ...,
    ) -> None: ...
    @property
    def min_batch_size(self) -> int: ...
    @property
    def chunk_size(self) -> int: ...
    @property
    def max_threads(self) -> int: ...
    @property
    def use_thread_pool(self) -> bool: ...

class Tokenizer:
    def count(self, input: str) -> int: ...
    def count_till_limit(self, input: str, limit: int) -> int | None: ...
    def encode(
        self, input: str, allowed_special: set[str] | None = ...
    ) -> list[int]: ...
    def encode_batch(
        self, texts: list[str], allowed_special: set[str] | None = ...
    ) -> tuple[list[list[int]], int, float]: ...
    def encode_batch_parallel(
        self,
        texts: list[str],
        options: ParallelOptions | None = ...,
        allowed_special: set[str] | None = ...,
    ) -> tuple[list[list[int]], int, float, int]: ...
    def encode_split_chunks_parallel(
        self,
        input: str,
        chunk_size: int = ...,
        options: ParallelOptions | None = ...,
        allowed_special: set[str] | None = ...,
    ) -> tuple[list[list[int]], int, float, int]: ...
    def decode(self, tokens: list[int]) -> str | None: ...
    def decode_batch(self, batch_tokens: list[list[int]]) -> list[str | None]: ...
    def decode_batch_parallel(
        self, batch_tokens: list[list[int]], options: ParallelOptions | None = ...
    ) -> list[str | None]: ...
    def split(
        self, input: str, allowed_special: set[str] | None = ...
    ) -> list[str]: ...
    def split_chunks(
        self,
        input: str,
        chunk_size: int = 64,
        allowed_special: set[str] | None = ...,
    ) -> list[str]: ...
    def apply_chat_template(
        self,
        messages: list[dict[str, object]],
        thinking_mode: str = "chat",
        context: list[dict[str, object]] | None = ...,
        drop_thinking: bool = True,
        add_default_bos_token: bool = True,
        tools: list[dict[str, object]] | None = ...,
        add_generation_prompt: bool = True,
    ) -> str: ...
    @property
    def special_tokens(self) -> dict[str, int] | None: ...
    @property
    def vocab_size(self) -> int: ...

def cl100k_base() -> Tokenizer: ...
def o200k_base() -> Tokenizer: ...
def deepseek_base() -> Tokenizer: ...
def deepseek_32() -> Tokenizer: ...
def kimi_k2() -> Tokenizer: ...
def is_cached_cl100k() -> bool: ...
def is_cached_deepseek() -> bool: ...
def is_cached_deepseek_32() -> bool: ...
def is_cached_kimi_k2() -> bool: ...
def is_cached_o200k() -> bool: ...
def get_num_threads() -> int: ...
